# fly.toml app configuration file generated for trackitall-react on 2024-10-29T12:36:16-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trackitall-react'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
