export const LEETCODE_SUPPORTED_LANGUAGES: string[] = [
  "c",
  "c#",
  "c++",
  "dart",
  "elixir",
  "erlang",
  "go",
  "java",
  "javascript",
  "kotlin",
  "php",
  "python",
  "racket",
  "ruby",
  "rust",
  "scala",
  "swift",
  "typescript",
];

export const LEETCODE_TAGS: string[] = [
  "Array",
  "Hash Table",
  "Linked List",
  "Math",
  "Recursion",
  "String",
  "Sliding Window",
  "Binary Search",
  "Divide And Conquer",
  "Two Pointers",
  "Dynamic Programming",
  "Greedy",
  "Trie",
  "Sorting",
  "Backtracking",
  "Stack",
  "Heap (Priority Queue)",
  "Merge Sort",
  "String Matching",
  "Bit Manipulation",
  "Matrix",
  "Monotonic Stack",
  "Simulation",
  "Combinatorics",
  "Memoization",
  "Tree",
  "Depth-First Search",
  "Binary Tree",
  "Binary Search Tree",
  "Breadth-First Search",
  "Union Find",
  "Graph",
  "Design",
  "Doubly-Linked List",
  "Geometry",
  "Interactive",
  "Bucket Sort",
  "Radix Sort",
  "Counting",
  "Data Stream",
  "Iterator",
  "Database",
  "Rolling Hash",
  "Hash Function",
  "Shell",
  "Enumeration",
  "Number Theory",
  "Topological Sort",
  "Prefix Sum",
  "Quickselect",
  "Binary Indexed Tree",
  "Segment Tree",
  "Line Sweep",
  "Ordered Set",
  "Queue",
  "Monotonic Queue",
  "Counting Sort",
  "Brainteaser",
  "Game Theory",
  "Eulerian Circuit",
  "Bitmask",
  "Randomized",
  "Reservoir Sampling",
  "Shortest Path",
  "Rejection Sampling",
  "Probability And Statistics",
  "Suffix Array",
  "Concurrency",
  "Minimum Spanning Tree",
  "Biconnected Component",
  "Strongly Connected Component",
];
